package api

import (
	"encoding/json"
	"errors"
	"strings"
	"testing"

	"infini.sh/framework/core/elastic"
)

func TestGetClusterCredentialDisplayName(t *testing.T) {
	tests := []struct {
		name     string
		cluster  string
		kind     string
		wantName string
	}{
		{
			name:     "platform credential name",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindPlatform,
			wantName: "easysearch-test-cluster (Platform)",
		},
		{
			name:     "agent credential name",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindAgent,
			wantName: "easysearch-test-cluster (Agent)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := getClusterCredentialDisplayName(tt.cluster, tt.kind); got != tt.wantName {
				t.Fatalf("expected %q, got %q", tt.wantName, got)
			}
		})
	}
}

func TestIsAutoGeneratedClusterCredentialName(t *testing.T) {
	const clusterID = "d7vd5sr0ebik06gvpjd0"
	tests := []struct {
		name     string
		credName string
		cluster  string
		kind     string
		want     bool
	}{
		{
			name:     "matches new platform format",
			credName: "easysearch-test-cluster (Platform)",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindPlatform,
			want:     true,
		},
		{
			name:     "matches legacy agent format",
			credName: "easysearch-test-cluster_agent(d7vd5sr0ebik06gvpjd0)",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindAgent,
			want:     true,
		},
		{
			name:     "ignores custom names",
			credName: "production readonly credential",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindPlatform,
			want:     false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isAutoGeneratedClusterCredentialName(tt.credName, tt.cluster, clusterID, tt.kind); got != tt.want {
				t.Fatalf("expected %v, got %v", tt.want, got)
			}
		})
	}
}

func TestEnsureManagedAgentCollectionCredentialSkipsAgentlessWithoutPlatformAuth(t *testing.T) {
	conf := &elastic.ElasticsearchConfig{
		Distribution:         elastic.Easysearch,
		MetricCollectionMode: elastic.ModeAgentless,
	}

	if err := ensureManagedAgentCollectionCredential(conf, ""); err != nil {
		t.Fatalf("expected agentless cluster without platform auth to be skipped, got %v", err)
	}
}

func TestEnsureManagedAgentCollectionCredentialRequiresPlatformAuthInAgentMode(t *testing.T) {
	conf := &elastic.ElasticsearchConfig{
		Distribution:         elastic.Easysearch,
		MetricCollectionMode: elastic.ModeAgent,
	}

	err := ensureManagedAgentCollectionCredential(conf, "")
	if err == nil {
		t.Fatal("expected error when agent mode cluster has no platform auth")
	}
	if !strings.Contains(err.Error(), "platform credential is required") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestEnsureManagedAgentCollectionCredentialSkipsUnsupportedDistribution(t *testing.T) {
	conf := &elastic.ElasticsearchConfig{
		Distribution:         elastic.Elasticsearch,
		MetricCollectionMode: elastic.ModeAgent,
	}

	if err := ensureManagedAgentCollectionCredential(conf, ""); err != nil {
		t.Fatalf("expected unsupported distribution to be skipped, got %v", err)
	}
}

func TestBuildAgentCollectionRoleBody(t *testing.T) {
	var body struct {
		Cluster []string `json:"cluster"`
		Indices []struct {
			Names      []string `json:"names"`
			Privileges []string `json:"privileges"`
		} `json:"indices"`
	}

	roleBody, err := buildAgentCollectionRoleBody(elastic.Easysearch)
	if err != nil {
		t.Fatalf("expected easysearch role body, got %v", err)
	}
	if err := json.Unmarshal(roleBody, &body); err != nil {
		t.Fatalf("expected valid json body, got %v", err)
	}

	if len(body.Cluster) != 1 || body.Cluster[0] != "cluster_monitor" {
		t.Fatalf("expected cluster_monitor permission, got %#v", body.Cluster)
	}
	if len(body.Indices) != 1 {
		t.Fatalf("expected one indices permission block, got %#v", body.Indices)
	}
	if len(body.Indices[0].Names) != 1 || body.Indices[0].Names[0] != "*" {
		t.Fatalf("expected wildcard indices scope, got %#v", body.Indices[0].Names)
	}
	if len(body.Indices[0].Privileges) != 1 || body.Indices[0].Privileges[0] != "indices_monitor" {
		t.Fatalf("expected indices_monitor privilege, got %#v", body.Indices[0].Privileges)
	}
}

func TestBuildAgentCollectionRoleBodyRejectsUnsupportedDistribution(t *testing.T) {
	if _, err := buildAgentCollectionRoleBody(elastic.Elasticsearch); err == nil {
		t.Fatal("expected unsupported distribution error")
	}
}

func TestBuildAgentCollectionUserBodyRejectsUnsupportedDistribution(t *testing.T) {
	if _, err := buildAgentCollectionUserBody(elastic.Elasticsearch, "infini-agent", "secret"); err == nil {
		t.Fatal("expected unsupported distribution error")
	}
}

func TestWrapAgentCollectionProvisionErrorForEasysearchRoleAPI(t *testing.T) {
	err := wrapAgentCollectionProvisionError(
		elastic.Easysearch,
		"role",
		errors.New(`{"status":"NOT_FOUND","message":"Resource 'infini-agent' is not available."}`),
	)

	if err == nil {
		t.Fatal("expected wrapped error")
	}
	if !strings.Contains(err.Error(), "does not allow modifying _security/role") {
		t.Fatalf("expected actionable role api error, got %v", err)
	}
	if !strings.Contains(err.Error(), "security.restapi.roles_enabled") {
		t.Fatalf("expected config hint in error, got %v", err)
	}
}

func TestGetManagedAgentCollectionFallbackUsername(t *testing.T) {
	username, ok := getManagedAgentCollectionFallbackUsername(
		elastic.Easysearch,
		autoAgentCollectionUsername,
		errors.New(`{"status":"NOT_FOUND","message":"Resource 'infini-agent' is not available."}`),
	)
	if !ok {
		t.Fatal("expected fallback username for reserved infini-agent resource")
	}
	if username != autoAgentCollectionFallbackUsername {
		t.Fatalf("expected fallback username %q, got %q", autoAgentCollectionFallbackUsername, username)
	}
}

func TestGetManagedAgentCollectionFallbackUsernameSkipsCustomUser(t *testing.T) {
	if _, ok := getManagedAgentCollectionFallbackUsername(
		elastic.Easysearch,
		"custom-agent-user",
		errors.New(`{"status":"NOT_FOUND","message":"Resource 'custom-agent-user' is not available."}`),
	); ok {
		t.Fatal("expected no fallback for custom managed usernames")
	}
}
