package api

import (
	"strings"
	"testing"

	"infini.sh/framework/core/elastic"
)

func TestGetClusterCredentialDisplayName(t *testing.T) {
	tests := []struct {
		name     string
		cluster  string
		kind     string
		wantName string
	}{
		{
			name:     "platform credential name",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindPlatform,
			wantName: "easysearch-test-cluster (Platform)",
		},
		{
			name:     "agent credential name",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindAgent,
			wantName: "easysearch-test-cluster (Agent)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := getClusterCredentialDisplayName(tt.cluster, tt.kind); got != tt.wantName {
				t.Fatalf("expected %q, got %q", tt.wantName, got)
			}
		})
	}
}

func TestIsAutoGeneratedClusterCredentialName(t *testing.T) {
	const clusterID = "d7vd5sr0ebik06gvpjd0"
	tests := []struct {
		name     string
		credName string
		cluster  string
		kind     string
		want     bool
	}{
		{
			name:     "matches new platform format",
			credName: "easysearch-test-cluster (Platform)",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindPlatform,
			want:     true,
		},
		{
			name:     "matches legacy agent format",
			credName: "easysearch-test-cluster_agent(d7vd5sr0ebik06gvpjd0)",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindAgent,
			want:     true,
		},
		{
			name:     "ignores custom names",
			credName: "production readonly credential",
			cluster:  "easysearch-test-cluster",
			kind:     clusterCredentialKindPlatform,
			want:     false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isAutoGeneratedClusterCredentialName(tt.credName, tt.cluster, clusterID, tt.kind); got != tt.want {
				t.Fatalf("expected %v, got %v", tt.want, got)
			}
		})
	}
}

func TestEnsureManagedAgentCollectionCredentialSkipsAgentlessWithoutPlatformAuth(t *testing.T) {
	conf := &elastic.ElasticsearchConfig{
		Distribution:         elastic.Easysearch,
		MetricCollectionMode: elastic.ModeAgentless,
	}

	if err := ensureManagedAgentCollectionCredential(conf, ""); err != nil {
		t.Fatalf("expected agentless cluster without platform auth to be skipped, got %v", err)
	}
}

func TestEnsureManagedAgentCollectionCredentialRequiresPlatformAuthInAgentMode(t *testing.T) {
	conf := &elastic.ElasticsearchConfig{
		Distribution:         elastic.Easysearch,
		MetricCollectionMode: elastic.ModeAgent,
	}

	err := ensureManagedAgentCollectionCredential(conf, "")
	if err == nil {
		t.Fatal("expected error when agent mode cluster has no platform auth")
	}
	if !strings.Contains(err.Error(), "platform credential is required") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestEnsureManagedAgentCollectionCredentialSkipsUnsupportedDistribution(t *testing.T) {
	conf := &elastic.ElasticsearchConfig{
		Distribution:         elastic.Elasticsearch,
		MetricCollectionMode: elastic.ModeAgent,
	}

	if err := ensureManagedAgentCollectionCredential(conf, ""); err != nil {
		t.Fatalf("expected unsupported distribution to be skipped, got %v", err)
	}
}
