#存储极限数据平台相关数据的 Elasticsearch 集群信息，版本 v7.0+
elasticsearch:
  - name: default
    enabled: true
    monitored: false
    endpoint: http://localhost:9200
    basic_auth:
      username: elastic
      password: infinilabs

#前端 UI HTTP 配置
web:
  enabled: true
  embedding_api: true
  ui:
    enabled: true
    path: .public
    vfs: true
    local: true
  network:
    binding: 0.0.0.0:9000
    skip_occupied_port: true

elastic:
    elasticsearch: default
    enabled: true
    remote_configs: true
    health_check:
      enabled: true
    availability_check:
      enabled: false
    metadata_refresh:
      enabled: true
    store:
      enabled: true
    orm:
      enabled: true
      init_template: true
      template_name: ".infini"
      index_prefix: ".infini_"

metrics:
  enabled: true
  major_ip_pattern: "192.*"
  queue: metrics
  elasticsearch:
    enabled: true
    cluster_stats: true
    node_stats: true
    index_stats: true

pipeline:
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini_metrics"
          index_prefix: ".infini_"
          elasticsearch: "default"
          input_queue: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10
