elasticsearch:
  - name: default
    enabled: true
    endpoint: http://127.0.0.1:9200
    basic_auth:
      username: elastic
      password: ZBdkVQUUdF1Sir4X4BGB

web:
  enabled: true
  ui:
    enabled: true
    path: .public
    vfs: true
    local: true
  network:
    binding: 0.0.0.0:9000
    skip_occupied_port: true

elastic:
    elasticsearch: default
    enabled: true
    remote_configs: true
    store:
      enabled: true
    monitoring:
      enabled: true
    orm:
      enabled: true
      init_template: true
      template_name: ".infini-search-center"
      index_prefix: ".infini-search-center_"

search-center:
  ui_path: .public
  ui_vfs: true
  ui_local: true

metrics:
  major_ip_pattern: "192.*"
  queue: metrics
  elasticsearch:
    enabled: true
    cluster_stats: true
    node_stats: true
    index_stats: true

pipeline:
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini-search-center_metrics"
          elasticsearch: "default"
          input_queue: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10