version: "3.5"

services:
  infini-logging-build:
    # option 1: pull image from infini docker registry
    image: docker.infini.ltd:64443/nodejs-dev:latest

    # # option 2: build image locally
    # build: 
    #   context: ./
    #   dockerfile: ./Dockerfile
      
    ports:
      - 3000:3000
      - 8000:8000
    container_name: "infini-nodejs-dev"
    volumes:
      - ../src:/usr/src/app/src
      - ../config:/usr/src/app/config
      - ../mock:/usr/src/app/mock
      - ../package.json:/usr/src/app/package.json
      - ./entrypoint-dev.sh:/entrypoint.sh

volumes:
  dist: