security:
  enabled: true
  authc:
    realms:
      ldap:
        test: #setup guide: https://github.com/infinilabs/testing/blob/main/setup/gateway/cases/elasticsearch/elasticsearch-with-ldap.yml
          enabled: true
          host: "localhost"
          port: 3893
          bind_dn: "cn=serviceuser,ou=search,dc=infinilabs,dc=com"
          bind_password: "mysecret"
          base_dn: "dc=infinilabs,dc=com"
          user_filter: "(uid=%s)"
          #user_filter: "(&(uid=%s)(ou=技术))"
          group_attribute: "ou"
          bypass_api_key: true
          cache_ttl: "10s"
          role_mapping:
            anonymous: [ "ReadonlyUI" ]
            uid:
              "liugq@infinilabs.com": [ "ReadonlyUI" ]